### ISSUE TITLE
Partial parse results when there are syntax errors

### ISSUE THREAD

**Issue by jez** [lib-ruby-parser/lib-ruby-parser#16]
After correctness, the feature we value the most in Sorbet in a parser is actually error recovery (more than performance).

Partial parses for files with errors in them is critical, because it means we can provide things like auto-completion even in files with syntax errors (especially in files with syntax errors).

For example:

```ruby
def foo
  x.
end
```

this program has a syntax error in it, and Sorbet needs to be able to know that there's still a method called `foo` and a partially completed method call with a receiver of `x`.

Have you thought about error recovery in lib-ruby-parser? i.e.:

- it'd be great to have, but no plans to start work on it
- it would deviate from what the Ruby parser emits, so it's a non-goal
- it would be great to have, but would have to be prioritized below performance

etc. (maybe you have more thoughts)

Thanks!

**Comment by iliabylich** [comment]
Yesss, I was thinking about it a lot. What you posted above is not really about error recovery as I know. You want ALL tokens to be reduced and returned (in some way, aggregated into AST or not in this case), but error recovery is about treating a manual (using `yyerror`) or "automatic" error (like a wrong sequence of tokens) as a special `error` rule. Then, it can be specified in the grammar **how** and **where** these errors should be swallowed. So, to rephrase, error recovery mechanism usually throws away tokens:

```
stmts: stmts_list { ... }
     | error stmt { $$ = $2 } // throw away error at pos 1
```

Technically I believe it's possible to emit them in a special way (like an `Error` node with a sequence of tokens that produces it for example, but it's just a random idea)

Also, what's important, MRI uses this `error` non-terminal only in two places: `stmts` list and `top_stmts` list. This is why I believe it's possible to add more "error handlers" in other places without introducing reduce conflicts (simply because `error` non-terminal is very special in MRI's BNF).

And the last thing that is probably the most important in general (but not sure if it's useful for sorbet) is that MRI (and by the way whitequark/parser and lib-ruby-parser) don't fully restore from errors. By saying "fully" I mean broken state of the parser (like cmdarg/cond/many/many other guys). Simply imagine you are in a method, and so you have `DEF` pushed into `parser->context` (IIRC sorbet backported this feature from wq/parser), and for example the first statement produces an `error`, let's say it defines a constant.

What happens when you see closing `kEND`? Well, of course `error` is not `stmts` (`error stmt` is, but we have only one statement), and so `method_def: kDEF mid args stmts kEND` is not reduced, and thus  `DEF` is not popped from the `parser->context`. All subsequent constant definitions will be invalid and in general you'll get a bunch of method-body-specific errors while in fact you are not in a method. This is not-so-hard to fix by making a "snapshot" of the state (that is pretty small, just a `.size()` of each stack that represents some part of the state) after reducing `stmt`, but I guess that's not what need right now. It's more like a "nice to have" feature.

Let's get back to your example. It's actually even more different from error recovery than I expected. `lib-ruby-parser` (just like all other Ruby parsers that I know except for sorbet's parser) emit
+ `kDEF` "def"
+ `tIDENTIFIER` "foo"
+ `tIDENTIFIER` "x"
+ `tDOT` "."
+ `tIDENTIFIER` "end"
+ `EOF` ""

EOF is turned into `error` because there's no derivation that matches it (like at all), the rest of the AST is constructed, but later dropped:
```
Reducing stack by rule 443 (line 4011):
   $1 = nterm  "primary_value" ( Loc { begin: 10, end: 11 }: Node(Send(Send { recv: None, method_name: "x", args: [], dot_l: None, selector_l: Some(10...11), begin_l: None, end_l: None, operator_l: None, expression_l: 10...11 })) )
   $2 = nterm  "call_op" ( Loc { begin: 11, end: 12 }: Token([tDOT, String("."), 11...12]) )
   $3 = nterm  "operation2" ( Loc { begin: 13, end: 16 }: Token([tIDENTIFIER, String("end"), 13...16]) )
   $4 = nterm  "opt_paren_args" ( Loc { begin: 16, end: 16 }: OptParenArgs(OptParenArgs { begin_t: None, args: [], end_t: None }) )
-> $$ = nterm  "method_call" ( Loc { begin: 10, end: 16 }: Node(Send(Send { recv: Some(Send(Send { recv: None, method_name: "x", args: [], dot_l: None, selector_l: Some(10...11), begin_l: None, end_l: None, operator_l: None, expression_l: 10...11 })), method_name: "end", args: [], dot_l: Some(11...12), selector_l: Some(13...16), begin_l: None, end_l: None, operator_l: None, expression_l: 10...16 })) )
```

^ Scroll right a bit, there's `method_name: "end"` somewhere.

There's not much bison can do about it. I believe it's possible to dump a stack of the parser when error happens, would it be helpful?

If not, do you have any thoughts on what kind of data could be helpful? And also, how do you expect an output to look like?

I barely remember a change to sorbet's parser where `lexer.rl` was patched (by you?) to emit `tIDENTIFIER` for keywords after `.` char. That's not something I'd like to do here. I can't even imagine long-term consequences of such change. It works now, but nobody knows how it's going to be affected by upcoming changes from ruby/master.

**Comment by jez** [comment]
> I barely remember a change to sorbet's parser where `lexer.rl` was patched (by you?) to emit `tIDENTIFIER` for keywords after `.` char. That's not something I'd like to do here. I can't even imagine long-term consequences of such change. It works now, but nobody knows how it's going to be affected by upcoming changes from ruby/master.

i proposed introducing this change upstream to ruby when i met with the ruby types working group at rubyconf last year and he said he'd be willing to introduce a change like this upstream. i haven't gotten around to writing a patch.

**Comment by iliabylich** [comment]
What AST do you expect to get from this code?

**Comment by jez** [comment]
```
❯ >2 /dev/null sorbet -p parse-tree-whitequark  -e 'def foo
  puts "hello"
  y = x.
  return y
end'
zsh: permission denied: /dev/null

❯ 2> /dev/null sorbet -p parse-tree-whitequark  -e 'def foo
  puts "hello"
  y = x.
  return y
end'
s(:def, :foo, nil, nil)

❯ 2> /dev/null sorbet -p parse-tree-whitequark  -e 'def foo
  y = x.
  return y
end'
s(:def, :foo, nil, nil)

❯ 2> /dev/null sorbet -p parse-tree-whitequark  -e 'def foo
  y = x.
end'
s(:def, :foo, nil, nil)

❯ 2> /dev/null sorbet -p parse-tree-whitequark  -e 'def foo
  x.
end'
s(:def, :foo, nil, nil)
```

these results work well enough for now (we can at least see that there's still a method def

the absolute best case would be to see something like:

```ruby
s(:def, :foo, nil,
  s(:send,
    s(:send, nil, :x), :<error-no-method-name>))
```

**Comment by iliabylich** [comment]
Then I see two options:
1. add more **configurable** rules. I think it's ok to have them if they can be disabled , like `expr call_op tIDENTIFIER { if flag { ... } else { yyerror } }`
2. looks like your case could be resolved by adding something like a custom token rewriter. Maybe I'll have to add lexer's state into token, but it shouldn't affect performance. This way you'll be able to rewrite this `end` into what you need for sorbet.

Anyway, I don't want to rewrite the grammar so it doesn't match parse.y, but I understand that it's extremely valuable for LSP, and I'd like to have it as optional feature that is enabled when some `ParserOptions.lsp_mode` is set to `true`. 

I'll play with tomorrow and let you once I have something to share. How does it sound?

**Comment by jez** [comment]
That sounds great!

No rush at all btw, I started asking this question just for my own understanding of the goals of the project. Please only work on this if it's something you think would be interesting/valuable, because we're still a long way from having time to potentially switch to this in Sorbet (other things have higher priority right now).

Thanks again for the fast and open-minded responses.

**Comment by iliabylich** [comment]
Got it. Here's what I've got so far:

I was able to easily migrate [this](https://github.com/sorbet/sorbet/commit/f5cd2a8d4caee1dd64c1fd4c344e8171c871042c#diff-2bc2a3057bf285a676dee5eb5317ea8f314a31fde37e844210fb75392c4e4400) and [this](https://github.com/sorbet/sorbet/commit/16ec58d832441d87caf1b70c9428c1c26329bdb8#diff-38612ce8debb1951b7b292142439c264c1d5de754eb9a101b1ae4cebb0b2f459) changes. Now locally it works just like sorbet. I've added `%define parse.trace` bison directive and shift/reduce chain is exactly the same. But that's not something I'd like to apply here. First of all, it breaks 1 unit test, and what could be interesting for you, in this case sorbet emits a node that makes no sense for anyone except the grammar (try parsing `proc {_1; _1, foo = [nil, nil]}`, it returns an `assign` node that is not even documented anywhere because it's an intermediate node). I don't have many tests here for error recovering, but I'm sure it's completely different from MRI.

I feel that it's possible to do the change to the lexer by using something like a pluggable external tokens rewriter, I need to think about the API, but (just from the top of my head) it could be implemented as some kind of a function that is applied on every token that is passed from lexer to parser. It can take a `token + lex state` and return a new token (if rewrite is needed). Additionally there could be a field on a parser that holds an "external state" (which should also be passed to this function).

So that if you see `tNL` in `EXPR_DOT` state (that's the change to sorbet's lexer.rl) then you "swallow" it (rewriter should support it) and set something on the given state. Once you see `tIDENTIFIER` that matches a keyword **and** the flag is set on external state you rewrite it into a corresponding keyword. In this particular case it could like this:

```rust
struct SorbetState {
    got_nl_in_expr_dot: bool,
}

fn rewrite_token(token: Token, state: &mut SorbetState) -> (Token, RewriteAction) {
    if token.state_after.is_some(lex_states::EXPR_DOT) && token_name(token.token_type) == "tNL" {
        state.got_nl_in_expr_dot = true;
        return (token, RewriteAction::Drop);
    }

    if token.state_after.is_some(lex_states::EXPR_DOT)
        && state.got_nl_in_expr_dot
        && token_name(token.token_type) == "tIDENTIFIER"
    {
        state.got_nl_in_expr_dot = false;
        if let Some(keyword) = map_to_keyword(token.token_value.as_bytes()) {
            // rewrite
            token.token_type = keyword.token_type;
            return (token, RewriteAction::Keep);
        }
    }

    // instantly reset it otherwise
    state.got_nl_in_expr_dot = false;

    (token, RewriteAction::Keep)
}

let options = ParserOptions {
    token_rewriter: Box::new(rewrite_token)
    // other options ...
}
```

Yes, it requires `Parser` struct to be generic (parameterized by `<TExternalState>`), but I've already implemented it in the bison skeleton, so it requires absolutely no additional work. So far I feel like it's "the right" way to implement external overrides without breaking compatibility with MRI, both in terms of behavior and code.

The only somewhat problematic part is sorbet's change to the error recovery. Bison doesn't support `#ifdef` rules or any conditional rules at all. One potential solution that I see is rewriting `error` into `some-other-error` (honestly no idea how to call it) if some flag is enabled. This special "fake" non-terminal could replace a regular built-in `error` for sorbet and it could be used unambiguously to handle errors in a different way. This is 100% doable because I use custom bison skeleton (a-la rendering template).

> Please only work on this if it's something you think would be interesting/valuable

I totally get it, but in this case it's both interesting (for me personally) and valuable (for any kind of tool that provides LSP features).

**Comment by jez** [comment]
Nice, thanks for all the detail!

Completely understand about not wanting to break the test suite for something like this.

It sounds like you have a good grasp on what I had been asking for, and some concrete ideas for implementation.

Not sure how else I can help but if you have questions for me do let me know.

**Comment by iliabylich** [comment]
@jez https://github.com/lib-ruby-parser/lib-ruby-parser/pull/23 has a reference implementation of the new API. Also I've imported tests from sorbet, both AST and reported errors look the same. I'm not sure if it's a good idea to merge it, would be great if sorbet could have this code (all used APIs are public, so `SorbetTokenRewriter` can be easily extracted).
